### ISSUE TITLE
这个workflow不工作了

### ISSUE THREAD

**Issue by superlee** [zgs225/alfred-youdao#18]
出错信息：

> ./alfred-youdao work
[i] 2018/10/12 09:40:55 main.go:27: [./alfred-youdao work]
[i] 2018/10/12 09:40:55 agent.go:48: Cache count: 72
[i] 2018/10/12 09:40:55 agent.go:31: Cache miss
panic: Get https://openapi.youdao.com/api?appKey=2f871f8481e49b4c&from=auto&q=work&salt=GIehps&sign=2ef0e5a3ccc44f5174f97b0d4564b79c&to=auto: read tcp 10.136.56.11:49207->61.135.248.30:443: read: connection reset by peer

goroutine 1 [running]:
main.main()
	/Users/Yuez/Development/Go/src/github.com/zgs225/alfred-youdao/main.go:76 +0x1112

**Comment by zgs225** [comment]
这个可能是你那边的网络问题。现在还是不能工作吗？
